# -*- coding: utf-8 -*-
"""Predictive HR Analytics: Employee Attrition & Workforce Insights Using Python.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XExUBp1TT1Cg4xdWfDtfJIbY11cJO3GC

# Predictive HR Analytics: Employee Attrition & Workforce Insights Using Python

**Name** : Kushal Roy \
**PRN** : 220105011003

**Project Introduction**

Employee attrition is a critical challenge for organizations as it affects productivity, recruitment costs, and workforce stability. This project focuses on analyzing employee data to identify patterns and factors influencing attrition.

Using Python-based data analytics techniques, the project explores workforce trends, department-wise attrition, salary distribution, work-life balance impact, and predictive modeling. The analysis helps HR professionals make data-driven decisions to improve employee retention and workforce management.

Tools used in this project include Python, Pandas, NumPy, Matplotlib, Seaborn, and Scikit-learn.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the Dataset
df = pd.read_csv("hr_attrition_dataset_15000.csv")
df.head()

# Dataset Information
df.info()

# Summary Statistics
df.describe()

# Attrition Distribution
df["Attrition"].value_counts()

# Attrition Distribution Visualization
plt.figure()
sns.countplot(x="Attrition", data=df)
plt.title("Employee Attrition Distribution")
plt.show()

# Attrition by Department
plt.figure(figsize=(8,5))
sns.countplot(x="Department", hue="Attrition", data=df)
plt.xticks(rotation=45)
plt.title("Department-wise Attrition")
plt.show()

# Salary vs Attrition
plt.figure(figsize=(8,5))
sns.boxplot(x="Attrition", y="Salary", data=df)
plt.title("Salary Distribution by Attrition")
plt.show()

# Work-Life Balance Impact
plt.figure(figsize=(8,5))
sns.countplot(x="WorkLifeBalance", hue="Attrition", data=df)
plt.title("Work-Life Balance vs Attrition")
plt.show()

# Correlation Heatmap
plt.figure(figsize=(10,6))
sns.heatmap(df.corr(numeric_only=True), annot=True)
plt.title("Correlation Heatmap")
plt.show()

# Encode Categorical Data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Attrition"] = le.fit_transform(df["Attrition"])
df["Department"] = le.fit_transform(df["Department"])
df["JobRole"] = le.fit_transform(df["JobRole"])
df["Gender"] = le.fit_transform(df["Gender"])
df["Education"] = le.fit_transform(df["Education"])

# Define Features and Target
X = df.drop("Attrition", axis=1)
y = df["Attrition"]

# Train Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Define Features and Target
X = df.drop("Attrition", axis=1)
y = df["Attrition"]

# Train Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train Model
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

# Accuracy
accuracy = model.score(X_test, y_test)

print("Model Accuracy:", accuracy)

# Model Evaluation
from sklearn.metrics import classification_report

predictions = model.predict(X_test)

print(classification_report(y_test, predictions))

# Confusion Matrix visualization
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, predictions)

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt="d")
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# Advanced HR Analytics Modeling
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42
)
rf_model.fit(X_train, y_train)
rf_accuracy = rf_model.score(X_test, y_test)
print("Random Forest Accuracy:", rf_accuracy)

# Feature Importance
feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf_model.feature_importances_
})
feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)
feature_importance.head(10)

# Feature Importance Graph
plt.figure(figsize=(8,6))
sns.barplot(
    x="Importance",
    y="Feature",
    data=feature_importance.head(10)
)
plt.title("Top Factors Influencing Employee Attrition")
plt.show()

# Attrition Risk Prediction
attrition_probability = rf_model.predict_proba(X_test)[:,1]

risk_df = pd.DataFrame({
    "Actual": y_test,
    "Attrition_Risk": attrition_probability
})
risk_df.head()

# Employee Risk Segmentation
risk_df["Risk_Level"] = pd.cut(
    risk_df["Attrition_Risk"],
    bins=[0,0.3,0.6,1],
    labels=["Low Risk","Medium Risk","High Risk"]
)
risk_df["Risk_Level"].value_counts()

"""**HR Business Insights**

**Key Findings**

1. Employees with low work-life balance show higher attrition probability
2. Early-tenure employees show greater turnover risk
3. Salary levels strongly influence retention

**HR Recommendations**

1. Improve employee engagement programs
2. Strengthen retention for early-tenure employees
3. Implement salary benchmarking strategies
"""

# Model Comparison Table
from sklearn.metrics import accuracy_score
lr_pred = model.predict(X_test)
rf_pred = rf_model.predict(X_test)
lr_acc = accuracy_score(y_test, lr_pred)
rf_acc = accuracy_score(y_test, rf_pred)
comparison = pd.DataFrame({
    "Model": ["Logistic Regression", "Random Forest"],
    "Accuracy": [lr_acc, rf_acc]
})
comparison

# Model Comparison Table Optional visualization:
plt.figure()
sns.barplot(x="Model", y="Accuracy", data=comparison)
plt.title("Model Performance Comparison")
plt.show()

# ROC Curve (Professional Model Evaluation)
from sklearn.metrics import roc_curve, auc
probs = rf_model.predict_proba(X_test)[:,1]
fpr, tpr, threshold = roc_curve(y_test, probs)
roc_auc = auc(fpr, tpr)
plt.figure()
plt.plot(fpr, tpr, label="AUC = %0.2f" % roc_auc)
plt.plot([0,1],[0,1],'--')
plt.title("ROC Curve")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend()
plt.show()

# Department Attrition Rate Analysis
dept_attrition = df.groupby("Department")["Attrition"].mean()
dept_attrition

# Department Attrition Rate Analysis Visualization
plt.figure()
dept_attrition.plot(kind="bar")
plt.title("Attrition Rate by Department")
plt.ylabel("Attrition Rate")
plt.show()

# Tenure vs Attrition Analysis
plt.figure()
sns.boxplot(x="Attrition", y="YearsAtCompany", data=df)
plt.title("Tenure vs Attrition")
plt.show()

"""**Strategic** **HR Recommendations**
1. Develop targeted retention programs for employees with high attrition risk.
2. Improve work-life balance policies to reduce voluntary turnover.
3. Focus retention efforts on departments with the highest attrition rates.
4. Implement predictive HR dashboards to monitor workforce stability.
"""